app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', function () {
//
//    return view('dashboard.inicio');
//});
Route::group(['middleware' => ['language']], function () {
Route::resource('/','Home\HomeController');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);

Route::get('lang/{lang}', function ($lang) {
    session(['lang' => $lang]);
    return \Redirect::back();
})->where([
    'lang' => 'en|es'
]);

//// Registration routes...
//Route::get('auth/register', 'Auth\AuthController@getRegister');
//Route::post('auth/register', ['as' => 'auth/register', 'uses' => 'Auth\AuthController@postRegister']);

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email',['as'=>'password/email','uses'=>'Auth\PasswordController@postEmail']);

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');
Route::post('verEstatus',['as'=>'verEstatus','uses'=>'VerEstatusController@verEstatus']);

Route::group(['prefix'=>'maestros','namespace'=>'\Maestros'],function(){
    
    Route::resource('centros','CentroController');
    Route::resource('estados','EstadoController');
    Route::resource('localidades','LocalidadController');
    Route::resource('categorias','CategoriaController');
    Route::resource('proveedores','ProveedorController');
    Route::resource('servicios','ServicioController');
    Route::resource('tiposequipos','TipoEquipoController');
    Route::resource('usuarios','UserController');
    Route::get('estado','EstadoController@eliminar');
    Route::get('proveedorDelete','ProveedorController@eliminar');
    Route::get('buscarLocalidad','CentroController@buscarLocalidades');
    Route::get('centroEliminar','CentroController@destroy');
    Route::get('servicioAgregar','ServicioController@store');
    Route::get('servicioListar','ServicioController@index');
    Route::get('servicioEliminar','ServicioController@destroy');
    Route::get('tipoDelete','TipoEquipoController@destroy');

});
Route::group(['prefix'=>'inventario','namespace'=>'\Inventario'],function() {
    
    Route::resource('equipos','InventarioController' );
    Route::get('dropDownBuscarServicios','InventarioController@buscarServicios');
    Route::get('equipoEliminar','InventarioController@destroy');

});
Route::group(['prefix'=>'solicitudes','namespace'=>'\Solicitudes'],function(){
    Route::resource('solicitudservicio','SolicitudController');
    Route::get('equipoListar','SolicitudController@show');
    Route::get('equipoBuscar','SolicitudController@buscarEquipo');
    Route::get('solicitudGuardar','SolicitudController@store');
    Route::post('validarCampos', 'SolicitudController@validarCampos');
});
Route::group(['prefix'=>'autorizaciones','namespace'=>'\Autorizaciones'],function(){
   Route::resource('autorizacionservicio','AutorizacionController');

});
});

app/Http/Controllers/Maestros/CategoriaController.php
<?php

namespace dgmtm\Http\Controllers\Maestros;

use dgmtm\Categoria;
use dgmtm\Http\Requests\CreateCategoriaRequest;
use dgmtm\Http\Requests\CreateLocalidadRequest;
use dgmtm\Http\Requests\EditCategoriaRequest;
use dgmtm\Http\Requests\EditLocalidadRequest;
use dgmtm\Localidad;
use Exception;
use Illuminate\Http\Request;

use dgmtm\Http\Requests;
use dgmtm\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Session;
use PhpParser\Error;
use PhpSpec\Exception\Example\ErrorException;
use Symfony\Component\Debug\Exception\FatalErrorException;

class CategoriaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::orderBy('nomb_categoria', 'ASC')
            ->get();
        return view('maestros.categorias.index', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('maestros.categorias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoriaRequest $request)
    {

        try {
            $categoria = new Categoria();
            $categoria->nomb_categoria = mb_strtoupper($request->nomb_categoria);
            $categoria->save();
            $insert = trans('validation.attributes.message.insert');
            Session::flash('message', $insert);
            $bandera=1;
                        
        } catch (Exception $e) {
            $error = trans('validation.attributes.message.error');
            Session::flash('message', $error.$e);
            $bandera=0;
        }
        Session::flash('bandera',$bandera);
        return redirect()->route('maestros.categorias.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria=Categoria::findOrFail($id);
        return view('maestros.categorias.edit',compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditCategoriaRequest $request, $id)
    {
        $categoria=Categoria::findOrFail($id);
        $categoria->nomb_categoria=mb_strtoupper($request->nomb_categoria);
        $categoria->save();
        $update=trans('validation.attributes.message.update');
        $bandera='update';
        Session::flash('message',$update);
        Session::flash('bandera',$bandera);
        
        return redirect()->route('maestros.categorias.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $categoria=Categoria::findOrFail($id);
        $categoria->delete();
        $message=trans('validation.attributes.message.delete');
        $nombre=$categoria->nomb_categoria;
        $delete=$message.' a la categoria '.$nombre;
        $bandera='delete';
        Session::flash('message',$delete);
        Session::flash('bandera',$bandera);
        if($request->ajax())
        {
            return response()->json([
               'message'=>$delete 
            ]);
                
        }
        return redirect()->route('maestros.categorias.index');

    }
}

app/Http/Controllers/Maestros/CentroController.php
<?php

namespace dgmtm\Http\Controllers\Maestros;

use dgmtm\Categoria;
use dgmtm\Centro;
use dgmtm\Estado;
use dgmtm\Http\Requests\CreateCentroRequest;
use dgmtm\Http\Requests\EditCentroRequest;
use dgmtm\Localidad;
use Illuminate\Http\Request;

use dgmtm\Http\Requests;
use dgmtm\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;

class CentroController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $centros = Centro::orderBy('nomb_centro', 'ASC')
            ->with('estado', 'localidad', 'categoria')
            ->get();

        return view('maestros.centros.index', compact('centros'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias=Categoria::orderBy('nomb_categoria','ASC')->lists('nomb_categoria','id');
        $estados=Estado::select('estados.id','estados.nomb_estado')
           /* ->join('localidades','estados.id','=','localidades.estado_id')*/
            ->with('localidad')
            ->orderBy('nomb_estado','ASC')
            ->lists('nomb_estado','id');

       
        return view('maestros.centros.create',compact('categorias','estados'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCentroRequest $request)
    {
        $centro=new Centro();
        $centro->nomb_centro=mb_strtoupper($request->nomb_centro);
        $centro->director_centro=mb_strtoupper($request->director_centro);
        $centro->categoria_id=mb_strtoupper($request->categoria_id);
        $centro->estado_id=mb_strtoupper($request->estado_id);
        $centro->localidad_id=mb_strtoupper($request->localidad_id);
        $centro->save();
        $insert=trans('validation.attributes.message.insert');
        $bandera='insert';
        Session::flash('bandera',$bandera);
        Session::flash('message',$insert);
        return redirect()->route('maestros.centros.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $centro=Centro::findOrFail($id);
        $categorias=Categoria::orderBy('nomb_categoria','ASC')->lists('nomb_categoria','id');
        $estados=Estado::select('estados.id','estados.nomb_estado')
            ->with('localidad')
            ->orderBy('nomb_estado','ASC')
            ->lists('nomb_estado','id');
        $localidades=Localidad::select('localidades.id','localidades.nomb_localidad')
            ->with('estado')
            ->where('localidades.estado_id','=',$centro->estado_id)
            ->orderBy('nomb_localidad','ASC')
            ->lists('nomb_localidad','id');
        return view('maestros.centros.edit',compact('centro','categorias','estados','localidades'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditCentroRequest $request, $id)
    {
        $centro=Centro::findOrFail($id);
        $centro->nomb_centro=mb_strtoupper($request->nomb_centro);
        $centro->director_centro=mb_strtoupper($request->director_centro);
        $centro->categoria_id=($request->categoria_id);
        $centro->estado_id=mb_strtoupper($request->estado_id);
        $centro->localidad_id=($request->localidad_id);
        $centro->save();
        $update=trans('validation.attributes.message.update');
        $bandera='update';
        Session::flash('message',$update);
        Session::flash('bandera',$bandera);
        return redirect()->route('maestros.centros.index');

        /*if($request->ajax())
        {
            $centro=Centro::findOrFail($request->id);
            $centro->nomb_centro=mb_strtoupper($request->nombCentro);
            $centro->director_centro=mb_strtoupper($request->dirNombre);
            $centro->categoria_id=($request->categoriaId);
            $centro->estado_id=mb_strtoupper($request->estadoId);
            $centro->localidad_id=($request->localidadId);
            $centro->save();
            $update=trans('validation.attributes.message.update');
            return response()->json([
                'message'=>$update

            ]);
          
        }*/
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        if($request->ajax())
        {
            $centro=Centro::findOrFail($request->id);
            $centro->delete();
            $message=trans('validation.attributes.message.delete');
            $nombre=$centro->nomb_centro;
            $delete=$message.' al centro de atención '.$nombre;

            return response()->json([
               'message'=>$delete,
            ]);

        }
        

    }

    public function buscarLocalidades(Request $request)
    {
       /* $id=Input::get('option');
        $localidades=Estado::find($id)->localidad;
        return $localidades->lists('nomb_localidad','id');*/
        
        if($request->ajax())
        {
            
            $id=$request->id;
            $localidades=Estado::find($id)->localidad;
           return $localidades->lists('nomb_localidad','id');
           
                
        }
       
    }
}

app/Http/Controllers/Maestros/EquipoController.php
<?php

namespace dgmtm\Http\Controllers\Maestros;

use Illuminate\Http\Request;

use dgmtm\Http\Requests;
use dgmtm\Http\Controllers\Controller;

class EquipoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Maestros/UserController.php
<?php

namespace dgmtm\Http\Controllers\Maestros;

use dgmtm\Http\Requests\CreateUserRequest;
use dgmtm\User;
use Illuminate\Http\Request;

use dgmtm\Http\Requests;
use dgmtm\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios=User::orderBy('id','DESC')
            ->get();
        return view('maestros.usuarios.index',compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('auth.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $usuario=new User();
        $usuario->name=mb_strtoupper($request->name);
        $usuario->email=$request->email;
        $usuario->password=bcrypt($request->password);
        $usuario->perfil_user=$request->perfil_user;
        $usuario->save();
        $insert=trans('validation.attributes.message.insert');
        $bandera='insert';
        Session::flash('bandera',$bandera);
        Session::flash('message',$insert);
        return redirect()->route('maestros.usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
    
}

resources/views/maestros/proveedores/create.blade.php
@extends('maestros.proveedores')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4>Datos del proveedor</h4></div>

                    <div class="panel-body">
                        @include('mensajes.validation')
                        {!! Form::open(['route'=>'maestros.proveedores.store','method'=>'POST','class'=>'']) !!}
                        @include('maestros.proveedores.partials.fields')
                        <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            {!! Form::submit('Guardar',['id'=>'guardar','class'=>'btn btn-success col-lg-1 col-xs-12 col-sm-2 col-md-2 incluir']) !!}
                            {!! Html::link(route('maestros.proveedores.index'),'Cancelar',['class'=>'btn btn-primary col-lg-1 col-xs-12 col-sm-2 col-md-2 cancelar']) !!}
                        </div>
                        </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/maestros/proveedores/edit.blade.php
@extends('maestros.proveedores')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4>Editar datos del proveedor</h4></div>
                    <div class="panel-body">
                        @include('mensajes.validation')
                        {!! Form::model($proveedor,['route'=>['maestros.proveedores.update',$proveedor->id],'method'=>'PUT','class'=>'']) !!}
                        @include('maestros.proveedores.partials.fields')
                        <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                {!! Form::submit('Editar',['id'=>'editar','class'=>'btn btn-warning col-lg-1 col-xs-12 col-sm-2 col-md-2 editar']) !!}
                            {!! Form::close() !!}
                                @include('maestros.proveedores.partials.delete')
                        </div>
                        </div>


                        </div>

                    </div>
                </div>

            </div>

        </div>

    </div>
@endsection

resources/views/maestros/proveedores/index.blade.php
@extends('maestros.proveedores')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4>Lista de proveedores</h4></div>
                    @if(Session::has('message') && Session::has('bandera'))
                        @if(Session::get('bandera')==='update')
                            @include('mensajes.update')
                        @elseif(Session::get('bandera')==='delete')
                            @include('mensajes.delete')
                        @else
                            @include('mensajes.success')
                        @endif
                    @endif
                    <div class="panel-body">
                        <div class="table table-responsive">
                        <table id="proveedor" class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>RIF</th>
                                <th>Nombre</th>
                                <th>Telefono</th>
                                <th>Correo</th>
                                <th>Contacto</th>
                                <th>Acción</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($proveedores as $proveedor)
                                <tr data-id="{{$proveedor->id}}">
                                    <td>{{$proveedor->id}}</td>
                                    <td>{{$proveedor->rif_proveedor}}</td>
                                    <td>{{$proveedor->nomb_proveedor}}</td>
                                    <td>{{$proveedor->telf_proveedor}}</td>
                                    <td>{{$proveedor->correo_proveedor}}</td>
                                    <td>{{$proveedor->contacto_proveedor}}</td>
                                    <td>
                                        <a href="{{route('maestros.proveedores.edit',$proveedor->id)}}">Editar</a>
                                        <a href="#" class="link-eliminar">Eliminar</a>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>

                        </table>
                        </div>
                        {{--{!! $proveedores->setPath('')->render() !!}--}}
                        <div>
                            <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <a href="{{route('maestros.proveedores.create')}}" class="btn btn-success col-lg-1 col-xs-12 col-sm-2 col-md-2 incluir" role="button">Incluir</a>
                                {!! Html::link('/','Cancelar',['target'=>'_parent','id'=>'Cancelar','class'=>'btn btn-primary col-lg-1 col-xs-12 col-sm-2 col-md-2 cancelar']) !!}
                            </div>
                            </div>
                        </div>

                    </div>




                </div>

            </div>


        </div>

    </div>

@endsection